### ISSUE TITLE
Preserve rotation style when converting to Leopard

### ISSUE THREAD

**Issue by PullJosh** [leopard-js/sb-edit#117]
Leopard has support for setting a sprite's initial rotation style, but sb-edit does not copy this setting over when converting a project.

**Comment by towerofnix** [comment]
On it!

Note to self - should be pretty easy, since sb-edit reads rotation style from (and writes it to) sb3, so has rotation style in the IR already. Serialization for initial sprite state is [here](https://github.com/leopard-js/sb-edit/blob/a9ce854aadd53e737c1cd8f7be7049912c7b416d/src/io/leopard/toLeopard.ts#L1899-L1914).
