### ISSUE TITLE
[question] How to use sb-edit

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [leopard-js/sb-edit#67]
I'm so confused as to how I can use this. The readme doesn't have clear instructions on how to use it. btw, I just want to get the leapord code of a scratch project that I can't upload onto scratch.

**Comment by suspecting** [comment]
Bump, but for a different reason.

I found a scratchR repo and a Ubuntu ISO that runs scratchr on launch. HOWEVER, neither the java or the flashplayer shows anything, which is why I want to use sb-edit.

**Comment by towerofnix** [comment]
I'm marginally late, but sb-edit isn't a standalone program. It's a library for various manipulations of Scratch projects (which for now is only really used for sb3 -> leopard conversion).

You can use an external tool like [sb-edit-playground](https://github.com/towerofnix/sb-edit-playground) to convert an sb3 project into Leopard locally. Skip the steps about `npm link`, since that's only for locally developing Leopard. Installing and then converting a project works like this:

```bash
cd /path/to/sb-edit-playground/
npm install
node index.js /path/to/your-project.sb3 leopard
```

You have to use a local web server to actually view the project:

```bash
cd /path/to/sb-edit-playground/ # if you aren't already there
cd ./out/leopard/
npx http-server -p 3001
# then navigate to http://localhost:3001/ in your web browser
```

Putting the output folder online somewhere should work too.
