### ISSUE TITLE
Cannot read properties of undefined (Reading "0")

### ISSUE THREAD

**Issue by Erisfiregamer1** [leopard-js/sb-edit#85]
Title, this error is causing me hell when trying to convert a friend's project using Leopard.
I tracked the error down to an IO library in the converter. The exact error spot is sb-edit/src/io/leopard/toLeopard.js:927.
Full error (Glitch.me, running project Colorlens by Yuski347):

/rbd/pnpm-volume/c3f6456c-ea9a-4017-ae1c-18ff3b9a1c5b/node_modules/sb-edit/lib/io/leopard/toLeopard.js:927
                })[0]
                  ^
TypeError: Cannot read properties of undefined (reading '0')
    at /rbd/pnpm-volume/c3f6456c-ea9a-4017-ae1c-18ff3b9a1c5b/node_modules/sb-edit/lib/io/leopard/toLeopard.js:927:19
    at Array.map (<anonymous>)
    at _loop_1 (/rbd/pnpm-volume/c3f6456c-ea9a-4017-ae1c-18ff3b9a1c5b/node_modules/sb-edit/lib/io/leopard/toLeopard.js:921:93)
    at Project.toLeopard (/rbd/pnpm-volume/c3f6456c-ea9a-4017-ae1c-18ff3b9a1c5b/node_modules/sb-edit/lib/io/leopard/toLeopard.js:949:9)

**Comment by towerofnix** [comment]
It's probably possible to just figure out which variable *would be* used and discard the rest (ex. maybe only the first definition of a variable is ever used in any case) but I don't really feel comfortable making an assumption about Scratch like that. I'm going to see if it's possible to support variables of the same name within sb-edit, then do a more intelligent sweep to only remove 100% unused (duplicate) variables in the `toLeopard` conversion.

**Comment by towerofnix** [comment]
I've got most of the bugs fixed now — I'm working on some runtime issues (in other words, the project is converting to Leopard without any issue, but the actual behavior isn't working 100% yet).

I'm not in charge of the Leopard website or the way that repositories work together, so once I get everything working, would it be OK if I just send you a zip file of the Leopard output? You can also run off of my sb-edit branch (looks like you've already figured out most of how to get Leopard working locally). It just may take a while longer before the fixes get actually pushed to the online Leopard website.

**Comment by Erisfiregamer1** [comment]
I'll just run the local Leopard instance. Give me some time to figure out how I'm going to run your sb-edit branch with it. (Thankfully I have Cloudflare R2)

**Comment by towerofnix** [comment]
No problem. Here's a build of the project in Leopard — I'll have the sb-edit and leopard PR's open soon. If you decide to run sb-edit locally (e.g. because of further changes to the game), you might want to grab the `index.html` file from this zip anyway: I customized it to look a little nicer for a standalone game!

[(16 MB) colorlens.zip](https://github.com/leopard-js/sb-edit/files/10761904/colorlens.zip)

**Comment by Erisfiregamer1** [comment]
My friend will be very happy about this once I get it running on Glitch. :D

**Comment by Erisfiregamer1** [comment]
UPDATE: Oh god, it's broken, it's broken as fuck.
I'm using Leopard from unpkg and it's not working at all ;(

[https://zircon-incongruous-tarascosaurus.glitch.me](https://zircon-incongruous-tarascosaurus.glitch.me) (Project link)

**Comment by towerofnix** [comment]
Yeah. Um, I assumed `index.esm.js` got automatically bundled into the output directory, which... it deffo does not! Oops.

Here's mine for now: [dist.zip](https://github.com/leopard-js/sb-edit/files/10762355/dist.zip)

**Comment by Erisfiregamer1** [comment]
Time to run ***the sed command*** again. Fun :D

**Comment by Erisfiregamer1** [comment]
Okay, it works now! But the font broke. Help?

**Comment by towerofnix** [comment]
No problem!

> Okay, it works now! But the font broke. Help?

What browser are you working with? In Chrome the costume fonts seem to render correctly for me. There may be browser differences, that's why I'm pointing you to try Chrome if you're on another browser.

Also, that's weird. I don't see that error at all on my end. It looks like it has to do with speech/thought bubbles, which I don't think the project uses at all?

**Comment by Erisfiregamer1** [comment]
Chromebook :/

The project URL (if you want to test it, maybe?) is https://zircon-incongruous-tarascosaurus.glitch.me/

**Comment by towerofnix** [comment]
Dang, no issues at all for me running yours — just the same as when I run it locally.

Can you tell me [what version of Chrome OS you're using?](https://www.whatismybrowser.com/detect/what-version-of-chrome-os-do-i-have)

Also, I feel like it's just the last 5 years or so that a new generation of young people programming on Chromebooks (usually gotten for school I'm guessing?). You guys are inspirational, and brave :P

**Comment by Erisfiregamer1** [comment]
ChromeOS 109. I also have access to a 103 chromebook (It hit AUE, it's my school loaner LMAO) and it has the same problems...

**Comment by towerofnix** [comment]
Oh, actually, sorry for the confusion here ^^;; I spent so much time looking at the version of Colorwell that loaded through Leopard that I didn't realize the fonts *weren't* loading in correctly.

<img width="502" alt="Colorlens main menu; logo and buttons all use serif font" src="https://user-images.githubusercontent.com/9948030/219661905-1fe88a9d-f8ea-4c8d-add6-1be76b0aa68f.png">

It turns out we just don't support fonts in SVGs yet. See leopard-js/leopard#107. Sorry for the inconvenience! You'll have to make a remix with these costumes converted to bitmap if you want the fonts to show (they'll look a little pixelated, but until we add proper font support, that's probably the best you can do).

By the way, my Leopard and sb-edit pull requests are open now. See #90 (sb-edit branch `compat` on [my fork](https://github.com/towerofnix/sb-edit)) and leopard-js/leopard#157 (leopard branch `compat-support` on [my fork](https://github.com/towerofnix/leopard)). I use [sb-edit-playground](https://github.com/towerofnix/sb-edit-playground) as a straightforward utility to make linking `sb-edit` and `leopard` easier, just see the README there (as long as you're familiar with the command line, assuming glitch.me gives you CLI access).

As for the "cannot destructure" issue, I looked around the code path leading there, and it seems like some sprite's `costume` is being set to undefined. That generally shouldn't be happening. Since I can't reproduce it, I'm guessing it's an issue with loading the costume files on your device — since we're both using basically the same web browser, maybe Glitch.me had a temporary caching issue. Can you try [clearing your cached images and files](https://chromeunboxed.com/how-to-get-a-cache-free-refresh-on-your-chromebook/) (just make sure to deselect your history and other settings!!), then opening your glitch.me link again? Alternatively you could try putting the built files on a different host, like GitHub pages.

**Comment by Erisfiregamer1** [comment]
I've been getting hard-ratelimited by Glitch because of the SVGs, so Github will have to work I suppose.Can't wait to show my friend once it's all working- Wait, I found more bugs!- Player selection name (P1/P2 above the character telling you which is which) is missing- Settings back button causes the project to crash- Settings sliders all go 1-100 (I just want to be able to use my developer mode :[[[[)

**Comment by towerofnix** [comment]
- Player selection name (P1/P2 above the character telling you which is which) is missing

In the version I uploaded, I hid those — Leopard doesn't support resizing monitors or positioning them properly when the display canvas is bigger than the actual stage area (e.g. a 480x360 screen showing on a 960x720 webpage view).

You can enable them by searching for `.visible = true;` and uncommenting the relevant lines. See `MainMenu.js`, under `*whenIReceiveCharacterSelect() { ... }`, around line 350.

The variable watchers should show up when they're supposed to, but they won't be positioned quite right if your screen isn't super low resolution. :P

- Settings back button causes the project to crash
- Settings sliders all go 1-100

Yeah, I spotted your report on that (https://github.com/leopard-js/leopard/issues/156). I'll check both of these out this afternoon if I can!

**Comment by towerofnix** [comment]
- Settings back button causes the project to crash

This isn't a crash (no error), it's just a slight difference in the order Scratch and Leopard work with clones. In the "main menu" receiver, you broadcast "delete all clones" on the same frame as you create the new main menu clones. In Scratch, only the clones which existed at the time of the broadcast receive the message (and thus get deleted). In Leopard, *everything* extant on the *next* frame responds to the broadcast — including the ones which were just spawned! That's a compatibility issue, so I'll have a lookie at getting it resolved.

**Comment by towerofnix** [comment]
> And there's a new error, walking back with any character throws it:
>
> Uncaught TypeError: Cannot destructure property 'text' of 't' as it is undefined.
> at V._renderBubble (index.esm.js:23:33728)
> ...

While I couldn't reproduce this in your project myself, I found another project with a similar issue. I opened a PR fixing that one (leopard-js/leopard#160), which will hopefully fix your project as well — it turned out to be a compatibility issue instead of failed costume loading.

**Comment by Erisfiregamer1** [comment]
> > And there's a new error, walking back with any character throws it:
> > Uncaught TypeError: Cannot destructure property 'text' of 't' as it is undefined.
> > at V._renderBubble (index.esm.js:23:33728)
> > ...
> 
> While I couldn't reproduce this in your project myself, I found another project with a similar issue. I opened a PR fixing that one ([leopard-js/leopard#160](https://github.com/leopard-js/leopard/pull/160)), which will hopefully fix your project as well — it turned out to be a compatibility issue instead of failed costume loading.

Don't you hate it when stuff like that happens? Ah, whatever, can't complain- you've been *really* helpful in getting my friend a converted JS project. Now all I have to do is wait for your PRs to be merged...
